const indexOffsetByteWidth = 5;
const indexOffsetBitWidth = indexOffsetByteWidth * 8;
/* Max size of a tile is limited to 1MB which is enough for tilesets generated by the OpenMapTiles schema */
const indexEntryBitAlignedBitWidth = 20;
const maxTileSizeBitAlignedFragment = 2 ** indexEntryBitAlignedBitWidth - 1;

export default {
    indexOffsetByteWidth: indexOffsetByteWidth,
    indexOffsetBitWidth: indexOffsetBitWidth,
    bitAlignedFragment: {
        indexEntryBitWidth: indexEntryBitAlignedBitWidth,
        maxTileSize: maxTileSizeBitAlignedFragment,
    },
    byteAlignedFragment: {},
};
